import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { Resvg } from '@resvg/resvg-js';
import { config, title, description, displayName, initials, assetPath } from '../src/lib/config.ts';
import { detectIcon, isProfileLink } from '../src/lib/services.ts';
import { iconIds } from '../src/lib/services.ts';
import { verifyAppearance } from './verify-appearance.mjs';
import { createSharingImage, sharingImageUrl, sharingImageAlt } from '../src/lib/og.ts';

const html = await readFile('dist/index.html', 'utf8');
const escape = value => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
assert.equal((html.match(/<h1(?:\s|>)/g) || []).length, 1);
assert.ok(html.includes(escape(displayName)));
assert.ok(html.includes('@' + config.profile.username));
if (config.profile.title) {
  assert.ok(html.includes('<p class="profile-title">' + escape(config.profile.title) + '</p>'), 'Configured profile title is rendered as text');
} else {
  assert.ok(!html.includes('class="profile-title"'), 'Empty profile titles leave no markup');
}
assert.ok(html.includes('<title>' + escape(title) + '</title>'));
assert.equal((html.match(/class="link-card"/g) || []).length, config.links.length);
for (const link of config.links) assert.ok(html.includes('href="' + escape(link.url) + '"'));
for (const metadata of ['name="description"', 'rel="canonical"', 'property="og:title"', 'property="og:description"', 'property="og:image"', 'name="twitter:image"', 'name="twitter:card"', 'name="robots"', 'name="theme-color"']) assert.ok(html.includes(metadata), metadata);
assert.ok(html.includes(description));
assert.ok(html.includes('rel="canonical" href="' + config.site.url + '"'));
const png = await readFile('dist/og.png');
const { default: theme } = await import(new URL(`../src/themes/${config.site.theme}.ts`, import.meta.url));
const expectedImage = createSharingImage(config.profile, theme, config.site.mode);
assert.deepEqual(png, new Resvg(expectedImage.svg, expectedImage.options).render().asPng(), 'Built OG image respects configured theme and mode');
const image = sharingImageUrl(config.site.url, png);
assert.ok(html.includes('property="og:image" content="' + image + '"'));
assert.ok(html.includes('name="twitter:image" content="' + image + '"'));
assert.deepEqual(await readFile('dist/og/' + new URL(image).pathname.split('/').at(-1)), png, 'Fingerprinted image and compatibility alias have identical bytes');
const attribute = value => escape(value).replace(/"/g, '&quot;');
const alt = attribute(sharingImageAlt(config.profile));
assert.ok(html.includes('property="og:image:alt" content="' + alt + '"'));
assert.ok(html.includes('name="twitter:image:alt" content="' + attribute(sharingImageAlt(config.profile, 420)) + '"'));
assert.ok(html.includes('href="' + assetPath('favicon.svg') + '"'));
const person = JSON.parse(html.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)[1]);
assert.equal(person['@type'], 'Person');
assert.equal(person.name, displayName);
assert.equal(person.url, config.site.url);
assert.deepEqual(person.sameAs, config.links.filter(link => isProfileLink(link.url, link.icon || detectIcon(link.url))).map(link => link.url));
assert.ok((await readFile('dist/robots.txt', 'utf8')).includes(new URL('sitemap.xml', config.site.url).href));
assert.ok((await readFile('dist/sitemap.xml', 'utf8')).includes('<loc>' + config.site.url + '</loc>'));
const favicon = await readFile('dist/favicon.svg', 'utf8');
assert.ok(favicon.includes(initials(config.profile)));
assert.equal(favicon.includes('prefers-color-scheme:dark'), !config.site.mode, 'Static favicon respects configured appearance');
assert.ok(!favicon.includes('<rect'), 'Favicon has a transparent background');
assert.ok(favicon.includes('font-family="Arial, sans-serif"') && favicon.includes('font-weight="700"'), 'Favicon matches the portfolio monogram style');
assert.equal(png.readUInt32BE(16), 1200);
assert.equal(png.readUInt32BE(20), 630);
assert.ok(png.length > 1000);
assert.ok(html.includes('class="mode-toggle"'), 'Appearance switch is present');
assert.ok(html.includes('aria-label="Dark mode"'), 'Appearance switch has an accessible name');
verifyAppearance(html, config.site.mode);
assert.equal((html.match(/<script/g) || []).length, 3, 'Only JSON-LD, appearance initialization, and toggle JavaScript');
assert.ok(!/debug-theme|MutationObserver|queueMicrotask/.test(html), 'Production output excludes debug controls, theme styles, and runtime');
assert.ok(!html.includes('<img'), 'No avatar or preview images');
for (const anchor of html.matchAll(/<a\b[^>]*target="_blank"[^>]*>/g)) assert.ok(anchor[0].includes('rel="noopener noreferrer"'));
assert.ok((await readdir('src/themes')).includes(config.site.theme + '.ts'));
const iconFiles = await readdir('src/assets/icons');
for (const icon of iconIds) assert.ok(iconFiles.includes(icon + '.svg'), 'Local icon exists: ' + icon);
assert.ok(html.includes('href="' + assetPath('credits.txt') + '"'));
const credits = await readFile('dist/credits.txt', 'utf8');
for (const file of ['public/fonts/sources.json', 'public/fonts/OFL.txt', 'public/fonts/OFL-OpenSans.txt', 'public/fonts/OFL-SourceSans3.txt', 'public/fonts/OFL-Lora.txt', 'public/fonts/OFL-IBMPlexSans.txt', 'public/fonts/OFL-JetBrainsMono.txt', 'public/fonts/OFL-SpaceGrotesk.txt', 'public/fonts/OFL-Archivo.txt', 'src/assets/icons/simple-icons.txt', 'src/assets/icons/font-awesome.txt', 'src/assets/icons/lucide.txt']) assert.ok(credits.includes(await readFile(file, 'utf8')), 'Distributed license or provenance: ' + file);
console.log('Passed static content, local icons, generated favicon/OG, SEO, JSON-LD, robots, sitemap, safe links, appearance switch markup, and distributed asset licenses.');
